Feat(Mobile-scans): Added mobile scan and centralised security scans workflow configuration
studiographene/github-action-workflows pull request #17
Opened 2024-05-17 12:32 UTC by aakashdeshpandesg

Please include a summary of the changes and the related issue.
Please also include relevant motivation and context.
List any dependencies that are required for this change.

## Issue ticket number and link

## Type of change

Please check the relevant option.

-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

-   [ ] Tested the changed workflows in a repo

## Links to dependent PRs (if any)

Incase the current PR is dependent onto some other PR, please add the link to it.

## Checklist:

-   [ ] I have reviewed my code while raising this PR
-   [ ] I have added comments to my code, particularly in hard-to-understand areas
-   [ ] I have created a new README file named as `README-<name-of-the-workflow-file>.md` in case of new workflow addition,  or made corresponding changes to the documentation with respect to the changes.
-   [ ] My changes generate no new warnings and errors

2024-05-17 13:12 UTC, mohankumar-studiographene requested changes

2024-05-17 14:10 UTC, aakashdeshpandesg commented on .github/workflows/Security-scans.yml
> +            echo "SKIP_STEP=true" >> $GITHUB_OUTPUT
done

2024-05-17 14:10 UTC, aakashdeshpandesg commented on .github/workflows/Security-scans.yml
> +          if [ -f composer.lock ] || [ -f composer.json ]; then
done

2024-05-21 05:35 UTC, aakashdeshpandesg reviewed
feat(license-scan): Updated config for allowedLicenses.txt

2024-05-23 08:52 UTC, merged